"""schema initial

Revision ID: 885815213e70
Revises: 
Create Date: 2026-09-27 17:28:03.021698

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885815213e70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_slug'), 'sites', ['slug'], unique=True)
    op.create_table('species_names',
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('common_name_fr', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('scientific_name')
    )
    op.create_table('species_sheets',
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('base_json', sa.String(), nullable=True),
    sa.Column('sheet_json', sa.String(), nullable=True),
    sa.Column('has_sheet', sa.Boolean(), nullable=False),
    sa.Column('loaded_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('scientific_name')
    )
    op.create_table('false_negative_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('reported_at', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('approx_time_utc', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tailscale_hostname', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('bridge_shared_secret_hash', sa.String(), nullable=False),
    sa.Column('bearer_token_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('decommissioned_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species_site_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('threshold_override', sa.Float(), nullable=True),
    sa.Column('redirect_to_scientific_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("rule IN ('present', 'impossible', 'redirect')", name='ck_species_site_rule_kind'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'scientific_name', name='uq_species_site_rules_site_species')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('node_local_id', sa.Integer(), nullable=False),
    sa.Column('detected_at_utc', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('raw_scientific_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_display_name', sa.String(), nullable=True),
    sa.Column('clip_name', sa.String(), nullable=True),
    sa.Column('has_clip', sa.Boolean(), nullable=False),
    sa.Column('redirected_to_scientific_name', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.String(), nullable=False),
    sa.Column('detected_local_date', sa.String(), nullable=False),
    sa.Column('detected_local_hour', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'node_local_id', name='uq_detections_node_local_id')
    )
    op.create_index('idx_detections_detected_at', 'detections', ['detected_at_utc'], unique=False)
    op.create_index('idx_detections_node_detected_at', 'detections', ['node_id', 'detected_at_utc'], unique=False)
    op.create_index('idx_detections_site_local_date', 'detections', ['site_id', 'detected_local_date'], unique=False)
    op.create_index('idx_detections_site_species', 'detections', ['site_id', 'scientific_name'], unique=False)
    op.create_table('node_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('delivered_at', sa.String(), nullable=True),
    sa.Column('applied_at', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('origin_type', sa.String(), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("kind IN ('set_species_threshold','exclude_species','unexclude_species','include_species','uninclude_species','reset_dynamic_threshold','set_main_name','mark_detection_reviewed','start_live','live_heartbeat','stop_live')", name='ck_node_command_kind'),
    sa.CheckConstraint("status IN ('pending','delivered','applied','failed','expired')", name='ck_node_command_status'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_status',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=True),
    sa.Column('last_heartbeat_at', sa.String(), nullable=True),
    sa.Column('last_detection_at', sa.String(), nullable=True),
    sa.Column('mic_device_name', sa.String(), nullable=True),
    sa.Column('mic_healthy', sa.Boolean(), nullable=True),
    sa.Column('disk_free_pct', sa.Float(), nullable=True),
    sa.Column('birdnet_go_pid_alive', sa.Boolean(), nullable=True),
    sa.Column('birdnet_go_reachable', sa.Boolean(), nullable=True),
    sa.Column('birdnet_go_version', sa.String(), nullable=True),
    sa.Column('bridge_version', sa.String(), nullable=True),
    sa.Column('node_db_max_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_thresholds_snapshot_json', sa.String(), nullable=True),
    sa.Column('dynamic_thresholds_snapshot_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('node_sync_state',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_detection_id', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('kept_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('spectrogram_path', sa.String(), nullable=True),
    sa.Column('rank_in_site_species', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.String(), nullable=True),
    sa.Column('evicted_at', sa.String(), nullable=True),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('missing_reason', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'scientific_name', 'detection_id', name='uq_kept_clips_site_species_det')
    )
    op.create_index('idx_kept_clips_lookup', 'kept_clips', ['site_id', 'scientific_name', 'evicted_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_detection', 'predictions', ['detection_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('synced_to_node_at', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('correct', 'false_positive')", name='ck_review_kind'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index('idx_predictions_detection', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_kept_clips_lookup', table_name='kept_clips')
    op.drop_table('kept_clips')
    op.drop_table('node_sync_state')
    op.drop_table('node_status')
    op.drop_table('node_commands')
    op.drop_index('idx_detections_site_species', table_name='detections')
    op.drop_index('idx_detections_site_local_date', table_name='detections')
    op.drop_index('idx_detections_node_detected_at', table_name='detections')
    op.drop_index('idx_detections_detected_at', table_name='detections')
    op.drop_table('detections')
    op.drop_table('species_site_rules')
    op.drop_table('nodes')
    op.drop_table('false_negative_reports')
    op.drop_table('species_sheets')
    op.drop_table('species_names')
    op.drop_index(op.f('ix_sites_slug'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
