"""commandes: origin_batch et last_command_batch pour regrouper un lot

Revision ID: eed8a20222f8
Revises: 885815213e70
Create Date: 2026-09-27 18:02:12.916805

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed8a20222f8'
down_revision: Union[str, None] = '885815213e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_commands', sa.Column('origin_batch', sa.String(), nullable=True))
    op.add_column('species_site_rules', sa.Column('last_command_batch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species_site_rules', 'last_command_batch')
    op.drop_column('node_commands', 'origin_batch')
    # ### end Alembic commands ###
